//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuthDCovid_19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_information_and_information_covid
    {
        public string name1 { get; set; }
        public string last_name { get; set; }
        public int id { get; set; }
        public string aaddress { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string pone { get; set; }
        public string mobile_phone { get; set; }
        public Nullable<System.DateTime> date_vac1 { get; set; }
        public string manufacturer_vac1 { get; set; }
        public Nullable<System.DateTime> date_vac2 { get; set; }
        public string manufacturer_vac2 { get; set; }
        public Nullable<System.DateTime> date_vac3 { get; set; }
        public string manufacturer_vac3 { get; set; }
        public Nullable<System.DateTime> date_vac4 { get; set; }
        public string manufacturer_vac4 { get; set; }
        public Nullable<System.DateTime> date_positive_result { get; set; }
        public Nullable<System.DateTime> date_recovery { get; set; }
    }
}
